namespace YtFlowApp
{
    [default_interface] runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();

        Windows.UI.Xaml.Controls.Frame ContentFrame;
    }

    [default_interface] runtimeclass HomePage : Windows.UI.Xaml.Controls.Page
    {
        HomePage();

        Windows.Foundation.Collections.IObservableVector<ProfileModel> Profiles
        {
            get;
        };
    }

    [default_interface] runtimeclass FirstTimePage : Windows.UI.Xaml.Controls.Page
    {
        FirstTimePage();
    }

    [default_interface] runtimeclass NewProfilePage : Windows.UI.Xaml.Controls.Page
    {
        NewProfilePage();
    }

    [default_interface] runtimeclass EditProfilePage : Windows.UI.Xaml.Controls.Page
    {
        EditProfilePage();
    }

    [default_interface] runtimeclass HomeProfileControl : Windows.UI.Xaml.Controls.UserControl
    {
        HomeProfileControl();

        ProfileModel Profile
        {
            get;
            set;
        };

        Windows.UI.Xaml.Controls.MenuFlyout MoreActionsFlyout;

        event Windows.Foundation.EventHandler<HomeProfileControl> ConnectRequested;
        event Windows.Foundation.EventHandler<HomeProfileControl> EditRequested;
        event Windows.Foundation.EventHandler<HomeProfileControl> DeleteRequested;
    }

    runtimeclass ProfileModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ProfileModel();

        UInt32 Id
        {
            get;
        };
        String Name
        {
            get;
            set;
        };
        String Locale
        {
            get;
            set;
        };
    }
    runtimeclass PluginModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        UInt32 Id
        {
            get;
        };
        UInt32 ProfileId
        {
            get;
        };
        String Name
        {
            get;
            set;
        };
        String Desc
        {
            get;
            set;
        };
        String Plugin
        {
            get;
            set;
        };
        UInt16 PluginVersion
        {
            get;
            set;
        };
        UInt8[] Param
        {
            get;
            set;
        };
    }
    runtimeclass EditPluginModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        EditPluginModel();

        PluginModel Plugin
        {
            get;
        };
        Boolean IsEntry
        {
            get;
            set;
        };
        Boolean IsNotEntry
        {
            get;
        };
        Boolean IsDirty
        {
            get;
            set;
        };
        Windows.Foundation.IStringable EditorParam
        {
            get;
            set;
        };
    }

    [default_interface] runtimeclass EditPluginTreeViewItemTemplateSelector
        : Windows.UI.Xaml.Controls.DataTemplateSelector
    {
        EditPluginTreeViewItemTemplateSelector();

        Windows.UI.Xaml.DataTemplate CategoryTemplate;
        Windows.UI.Xaml.DataTemplate PluginTemplate;
    }
}
