namespace YtFlowApp
{
    interface IHomeWidget
    {
        void UpdateInfo();
    };
    interface IPluginEditorParam
    {
        UInt8[] ToCbor();
        String[] CheckErrors();
    };

    [default_interface] runtimeclass RawEditorParam : IPluginEditorParam
    {
        String RawJson
        {
            get;
            set;
        };
    }

    [default_interface] runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();

        Windows.UI.Xaml.Controls.Frame ContentFrame;
    }

    [default_interface] runtimeclass HomePage : Windows.UI.Xaml.Controls.Page
    {
        HomePage();

        Windows.Foundation.Collections.IObservableVector<ProfileModel> Profiles
        {
            get;
        };
    }

    [default_interface] runtimeclass FirstTimePage : Windows.UI.Xaml.Controls.Page
    {
        FirstTimePage();
    }

    [default_interface] runtimeclass NewProfilePage : Windows.UI.Xaml.Controls.Page
    {
        NewProfilePage();

        Microsoft.UI.Xaml.Controls.RadioButtons SplitRoutingModeButtons
        {
            get;
        };
    }

    [default_interface] runtimeclass EditProfilePage : Windows.UI.Xaml.Controls.Page
    {
        EditProfilePage();

        Windows.UI.Xaml.Controls.ComboBox NewPluginTypeBox;
    }
    [default_interface] runtimeclass RawEditorPage : Windows.UI.Xaml.Controls.Page
    {
        RawEditorPage();
        EditPluginModel Model
        {
            get;
            set;
        };

        Windows.UI.Xaml.Media.SolidColorBrush PluginNameColor(Boolean hasNamingConflict);
    }
    [default_interface] runtimeclass LibraryPage : Windows.UI.Xaml.Controls.Page
    {
        LibraryPage();

        AssetModel Model
        {
            get;
        };
        Windows.UI.Xaml.Controls.GridView ProxyGroupGridView
        {
            get;
        };
    }
    [default_interface] runtimeclass AboutPage : Windows.UI.Xaml.Controls.Page
    {
        AboutPage();
    }

    [default_interface] runtimeclass HomeProfileControl : Windows.UI.Xaml.Controls.UserControl
    {
        HomeProfileControl();

        ProfileModel Profile
        {
            get;
            set;
        };

        Windows.UI.Xaml.Controls.MenuFlyout MoreActionsFlyout;

        event Windows.Foundation.EventHandler<HomeProfileControl> ConnectRequested;
        event Windows.Foundation.EventHandler<HomeProfileControl> EditRequested;
        event Windows.Foundation.EventHandler<HomeProfileControl> DeleteRequested;
    }

    [default_interface] runtimeclass NewProfileRulesetControl : Windows.UI.Xaml.Controls.ContentDialog
    {
        NewProfileRulesetControl();
        Boolean RulesetSelected
        {
            get;
        };
        String RulesetName
        {
            get;
        };
    }

    [default_interface] runtimeclass SplitRoutingRulesetControl : Windows.UI.Xaml.Controls.UserControl
    {
        SplitRoutingRulesetControl();

        static Windows.UI.Xaml.DependencyProperty RulesetNameProperty
        {
            get;
        };
        static Windows.UI.Xaml.DependencyProperty CanModifyRuleListProperty
        {
            get;
        };
        static Windows.UI.Xaml.DependencyProperty RuleListProperty
        {
            get;
        };

        String RulesetName
        {
            get;
            set;
        };
        Boolean CanModifyRuleList
        {
            get;
            set;
        };
        Windows.Foundation.Collections.IObservableVector<SplitRoutingRuleModel> RuleList
        {
            get;
            set;
        };

        event Windows.Foundation.TypedEventHandler<SplitRoutingRulesetControl, IInspectable> RemoveRequested;
    }

    [default_interface] runtimeclass NetifHomeWidget : Windows.UI.Xaml.Controls.UserControl, IHomeWidget
    {
        NetifHomeWidget();
    }

    [default_interface] runtimeclass SwitchHomeWidget : Windows.UI.Xaml.Controls.UserControl, IHomeWidget
    {
        SwitchHomeWidget();
    }

    [default_interface] runtimeclass DynOutboundHomeWidget : Windows.UI.Xaml.Controls.UserControl, IHomeWidget
    {
        DynOutboundHomeWidget();
    }

    [default_interface] runtimeclass ForwardHomeWidget : Windows.UI.Xaml.Controls.UserControl, IHomeWidget
    {
        ForwardHomeWidget();
    }

    runtimeclass ProfileModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ProfileModel();

        UInt32 Id
        {
            get;
        };
        String Name
        {
            get;
            set;
        };
        String Locale
        {
            get;
            set;
        };
    }
    runtimeclass PluginModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        UInt32 Id
        {
            get;
        };
        UInt32 ProfileId
        {
            get;
        };
        String Name
        {
            get;
            set;
        };
        String Desc
        {
            get;
            set;
        };
        String Plugin
        {
            get;
            set;
        };
        UInt16 PluginVersion
        {
            get;
            set;
        };
        UInt8[] Param
        {
            get;
            set;
        };
    }
    runtimeclass EditPluginModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        EditPluginModel();

        PluginModel Plugin
        {
            get;
        };
        Boolean IsEntry
        {
            get;
            set;
        };
        Boolean IsNotEntry
        {
            get;
        };
        Boolean IsDirty
        {
            get;
            set;
        };
        Boolean HasNamingConflict
        {
            get;
            set;
        };
        IPluginEditorParam EditorParam
        {
            get;
            set;
        };
    }
    runtimeclass SwitchChoiceItem : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SwitchChoiceItem();

        String Name
        {
            get;
            set;
        };
        String Description
        {
            get;
            set;
        };
        Boolean IsActive
        {
            get;
            set;
        };
    }
    runtimeclass ProxyModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        UInt32 Id
        {
            get;
        };
        String Name
        {
            get;
            set;
        };
        UInt8[] Proxy
        {
            get;
            set;
        };
        UInt16 ProxyVersion
        {
            get;
            set;
        };
    }
    runtimeclass ProxyGroupModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        UInt32 Id
        {
            get;
        };
        String Name
        {
            get;
            set;
        };
        String Type
        {
            get;
            set;
        };
        Boolean IsManualGroup
        {
            get;
        };
        Boolean IsSubscription
        {
            get;
        };
        String DisplayType
        {
            get;
        };
        String DisplayTypeIcon
        {
            get;
        };
        String TooltipText
        {
            get;
        };
        String SubscriptionUrl
        {
            get;
        };
        String SubscriptionUploadUsed
        {
            get;
        };
        String SubscriptionDownloadUsed
        {
            get;
        };
        String SubscriptionTotalUsed
        {
            get;
        };
        Double SubscriptionPercentUsed
        {
            get;
        };
        Boolean SubscriptionHasDataUsage
        {
            get;
        };
        String SubscriptionBytesTotal
        {
            get;
        };
        String SubscriptionRetrievedAt
        {
            get;
        };
        String SubscriptionExpireAt
        {
            get;
        };
        Windows.Foundation.Collections.IObservableVector<ProxyModel> Proxies
        {
            get;
            set;
        };
    }
    runtimeclass AssetModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        AssetModel();

        Windows.Foundation.Collections.IObservableVector<ProxyGroupModel> ProxyGroups
        {
            get;
            set;
        };
        Boolean IsProxyGroupsEmpty
        {
            get;
        };
        ProxyGroupModel CurrentProxyGroupModel
        {
            get;
            set;
        };
    }
    runtimeclass DynOutboundProxyModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        DynOutboundProxyModel();

        String Name
        {
            get;
        };
        String GroupName
        {
            get;
        };
    }

    enum SplitRoutingRuleDecision
    {
        Next,
        Direct,
        Proxy,
        Reject,
    };
    runtimeclass SplitRoutingRuleModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SplitRoutingRuleModel();

        String Rule
        {
            get;
            set;
        };
        SplitRoutingRuleDecision Decision
        {
            get;
            set;
        };
        Int32 DecisionIndex
        {
            get;
            set;
        };
    }

    [default_interface] runtimeclass EditPluginTreeViewItemTemplateSelector
        : Windows.UI.Xaml.Controls.DataTemplateSelector
    {
        EditPluginTreeViewItemTemplateSelector();

        Windows.UI.Xaml.DataTemplate CategoryTemplate;
        Windows.UI.Xaml.DataTemplate PluginTemplate;
    }
    [default_interface] runtimeclass BoolTemplateSelector : Windows.UI.Xaml.Controls.DataTemplateSelector
    {
        BoolTemplateSelector();

        Boolean Value
        {
            get;
            set;
        };

        Windows.UI.Xaml.DataTemplate TrueTemplate;
        Windows.UI.Xaml.DataTemplate FalseTemplate;
    }

    [default_interface] runtimeclass PluginTypeToDescConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        PluginTypeToDescConverter();
    }
    [default_interface] runtimeclass BoolToFontWeightConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        BoolToFontWeightConverter();
    }
    [default_interface] runtimeclass SplitRoutingModeToDescConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        SplitRoutingModeToDescConverter();
    }
}
